const homepageContent = {
  "research": [
    {
      "shortName": "Seed3D 2.0",
      "title": "Seed3D 2.0: Advancing High-Fidelity Simulation-Ready 3D Content Generation",
      "authors": [
        "Seed3D Team"
      ],
      "venue": "Technical Report, 2026",
      "image": "assets/research/seed3d-2-results.webp",
      "paper": "https://arxiv.org/abs/2605.13862",
      "project": "https://seed.bytedance.com/en/seed3d_2_0",
      "area": "Assets · Materials · Parts",
      "contribution": "Training-data construction, quality filtering, and processing pipelines across 3D assets.",
      "alt": "Seed3D 2.0 generated objects with their individual parts shown in distinct colors",
      "description": "A 3D generation system spanning detailed geometry, PBR materials, scene layouts, parts, and articulation.",
      "teamCredit": "Jiahang Liu · Core contributor",
      "video": "assets/videos/seed3d-2-parts.mp4",
      "videoPoster": "assets/videos/seed3d-2-parts.jpg",
      "videoCaption": "Part decomposition & assembly",
      "videoAlt": "A generated robot separates into its individual parts and reassembles."
    },
    {
      "shortName": "SceneSpinner",
      "title": "Taming LLMs for Codematic Indoor Scene Generation",
      "authors": [
        "Yixun Liang",
        "Qianyi Wu",
        "Chuan Fang",
        "Rui Chen",
        "Jiahang Liu",
        "Jianfeng Zhang",
        "Ping Tan"
      ],
      "venue": "ECCV 2026",
      "image": "assets/research/scenespinner.webp",
      "paper": "https://media.eventhosts.cc/Conferences/ECCV2026/pdfs/1860.pdf",
      "project": "https://eccv.ecva.net/virtual/2026/poster/3532",
      "area": "Scene generation",
      "alt": "SceneSpinner generated room shown from isometric, overhead, and interior views",
      "description": "Text-driven indoor scene generation through structured code, language-based planning, and instruction-aware training.",
      "projectLabel": "Conference",
      "displayName": "SceneSpinner"
    },
    {
      "shortName": "TopoMesh",
      "title": "TopoMesh: High-Fidelity Mesh Autoencoding via Topological Unification",
      "authors": [
        "Guan Luo",
        "Xiu Li",
        "Rui Chen",
        "Xuanyu Yi",
        "Jing Lin",
        "Chia-Hao Chen",
        "Jiahang Liu",
        "Song-Hai Zhang",
        "Jianfeng Zhang"
      ],
      "venue": "CVPR 2026",
      "image": "assets/research/topomesh.webp",
      "paper": "https://arxiv.org/abs/2603.24278",
      "project": "https://logan0601.github.io/projects/topomesh/index.html",
      "area": "Geometry representation",
      "alt": "Detailed mesh reconstructions produced by TopoMesh",
      "description": "Mesh autoencoding with a shared topology that enables direct supervision of geometry and preserves sharp detail."
    },
    {
      "shortName": "Pygmalion",
      "title": "Pygmalion: Bridging Reconstruction and Generation in Sparse Voxel-based 3D Modeling",
      "authors": [
        "Guan Luo",
        "Jing Lin",
        "Xuanyu Yi",
        "Jiahang Liu",
        "Song-Hai Zhang",
        "Jianfeng Zhang"
      ],
      "venue": "NeurIPS 2026",
      "image": "assets/research/pygmalion.webp",
      "project": "https://pygmalionanonymous.github.io/",
      "area": "3D generation",
      "alt": "Examples of 3D objects generated by Pygmalion",
      "description": "Sparse voxel representations that connect detailed reconstruction with robust 3D generation.",
      "video": "assets/videos/pygmalion-reconstruction.mp4",
      "videoPoster": "assets/videos/pygmalion-reconstruction.jpg",
      "videoCaption": "Detailed geometry reconstruction",
      "videoAlt": "A normal-colored reconstruction of a detailed robot rotates in 3D."
    },
    {
      "shortName": "Seed3D 1.0",
      "title": "Seed3D 1.0: From Images to High-Fidelity Simulation-Ready 3D Assets",
      "authors": [
        "Seed3D Team"
      ],
      "venue": "Technical Report, 2025",
      "image": "assets/research/seed3d-1.webp",
      "paper": "https://arxiv.org/abs/2510.19944",
      "project": "https://seed.bytedance.com/en/seed3d",
      "area": "3D asset generation",
      "contribution": "Data sourcing, curation, asset infrastructure, and training-data delivery.",
      "alt": "Seed3D generated 3D assets assembled into a scene",
      "description": "Single-image generation of 3D assets with geometry, textures, and physically based materials for simulation.",
      "teamCredit": "Jiahang Liu · Core contributor",
      "video": "assets/videos/seed3d-1-scene.mp4",
      "videoPoster": "assets/videos/seed3d-1-scene.jpg",
      "videoCaption": "Generated scene walkthrough",
      "videoAlt": "A moving camera shows a generated ancient-town scene at night."
    }
  ],
  "thesisImage": "assets/thesis/facial-animation-overview.png"
};
